on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
          run_install: true

      - name: Build
        shell: bash
        run: |
          pnpm build

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm config set access public
      - run: npm publish
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
